# Generated by Django 3.2.12 on 2022-04-11 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20220411_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de registro'),
        ),
    ]
