# Generated by Django 3.2.12 on 2022-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20220412_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cvitae',
            field=models.FileField(blank=True, null=True, upload_to='cvitae/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
